### ISSUE TITLE
Error initialization after upgrade

### ISSUE THREAD

**Issue by afraschetti** [OpenWebNet-HA/MyHOME#100]
After upgraded at the last version of MyHome in Home Assistant I had an error during the inizialitation phafe.
In the log trace I've the follow error:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
  File "/config/custom_components/myhome/__init__.py", line 71, in async_setup_entry
    _gateway_handler = hass.data[DOMAIN].pop(CONF_GATEWAY)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'gateway'
```
This is my configuration file.
[myhome.txt](https://github.com/anotherjulien/MyHOME/files/13112387/myhome.txt)

Someone can help me ?

Thanks

**Comment by afraschetti** [comment]
I 've this error also:

```
Traceback (most recent call last):
  File "/config/custom_components/myhome/__init__.py", line 69, in async_setup_entry
    tests_results = await hass.data[DOMAIN][entry.data[CONF_MAC]][CONF_ENTITY].test()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myhome/gateway.py", line 130, in test
    return await OWNSession(gateway=self.gateway, logger=LOGGER).test_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/OWNd/connection.py", line 240, in test_connection
    ) = await asyncio.open_connection(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('192.168.0.253', 20000)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myhome/__init__.py", line 71, in async_setup_entry
    _gateway_handler = hass.data[DOMAIN].pop(CONF_GATEWAY)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'gateway'
```

**Comment by GreenGrassBlueOcean** [comment]
Thank you for your contribution.

We are closing this ticket as part of the transition to the **[OpenWebNet-HA](https://github.com/OpenWebNet-HA)** community repository. This issue relates to legacy YAML configuration (`myhome.yaml`) or older Home Assistant versions that have been superseded by modern UI-based configuration and dynamic auto-discovery.

If you are running the modern integration on Home Assistant 2024+ and still encounter an issue, please feel free to open a fresh ticket with updated logs.
