### ISSUE TITLE
Error setting up entry F459 Gateway for myhome

### ISSUE THREAD

**Issue by githubsharezone** [OpenWebNet-HA/MyHOME#132]
i setting paramenter for myhome server but go erro . On log i see

raceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 561, in validate_dict
    raise er.DictInvalid('expected a dictionary', path)
voluptuous.error.DictInvalid: expected a dictionary

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myhome/__init__.py", line 62, in async_setup_entry
    _validated_config = config_schema(yaml.safe_load(await yaml_file.read()))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myhome/validate.py", line 177, in __call__
    data = super().__call__(data)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 276, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: expected a dictionary

**Comment by dave-hulpiau** [comment]
I have exactly the same problem.
My post on the community portal : https://community.home-assistant.io/t/legrand-bticino-myhome/229337/1035

**Comment by GreenGrassBlueOcean** [comment]
Resolved in [PR #232](https://github.com/OpenWebNet-HA/MyHOME/pull/232) (`v2-phase1-architecture`).

This issue was caused by changes in Home Assistant Core 2025/2026 (including `probatio` replacing `voluptuous` for nested schema validation, deprecated `config_entry` assignment in `OptionsFlowHandler`, and strict `myhome.yaml` path resolution).

In v2 Phase 1:
1. Schema validation in `validate.py` has been completely reworked and verified against HA Core 2025/2026.
2. Robust multi-path fallback for `myhome.yaml` has been implemented (checking `/config/myhome.yaml`, `/config/myhome/myhome.yaml`, and the custom component directory).
3. Options flow handler deprecations have been fully resolved.
4. Entity registration and dynamic discovery race conditions have been eliminated.
