### ISSUE TITLE
MYHOME stops to update data.

### ISSUE THREAD

**Issue by fab-70** [OpenWebNet-HA/MyHOME#45]
Hi all
periodically (few times a week) the integration stops to update data...  below the log of the error. Then i need to restart HA and all works properly.
I suppose this is a bug.  If this is due to my system, Is there a way to capture this event and automatically restart HA / MYHOME integration?
Many thanks for any feedback/suggestion.

Fabio

 

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/myhome/config_flow.py:402
Integration: MyHome (documentation, issues)
First occurred: 9:07:00 AM (2 occurrences)
Last logged: 9:07:04 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 203, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 230, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/myhome/config_flow.py", line 402, in async_step_ssdp
    discovery_info["port"] = None
TypeError: 'SsdpServiceInfo' object does not support item assignment

**Comment by fab-70** [comment]
Also these logs should help to explain the problem:


Logger: custom_components.myhome
Source: /usr/local/lib/python3.9/site-packages/OWNd/connection.py:584
Integration: MyHome (documentation, issues)
First occurred: 9:06:27 AM (1 occurrences)
Last logged: 9:06:27 AM
Connection interrupted, reconnecting...


Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 9:07:00 AM (1 occurrences)
Last logged: 9:07:00 AM

Detected integration that accessed discovery_info.__contains__() instead of discovery_info.upnp.__contains__() or discovery_info.ssdp_headers.__contains__(); this will fail in version 2022.6. Please report issue to the custom component author for myhome using this method at custom_components/myhome/config_flow.py, line 401: if "port" not in discovery_info:

**Comment by 1achy** [comment]
![Screenshot_20220206_122746_io homeassistant companion android](https://user-images.githubusercontent.com/6684654/152678700-302e1127-4e12-4256-a038-948610988196.jpg)
Same

**Comment by fab-70** [comment]
I managed adding a sensor calculating the seconds since last update of the energy sensor...  I then restart HA if 'last_update_age' >300
Hope this helps

Fabio


sensor:
  - platform: myhome
    devices:
      sensor_energia_51:
        where: '51'
        name: Energia 51
        class: power 
        manufacturer: bticino
        model: F52X
  - platform: template #additional sensor to manage disconnection of MyHome intergration
    sensors:
      last_update_age: 
        friendly_name: "Time since last update"
        value_template: "{{ (now() - states.sensor.energia_51_power.last_updated).total_seconds() | round(0) }}"
        unit_of_measurement: "Seconds"

**Comment by GreenGrassBlueOcean** [comment]
Thank you for reporting this issue.

This issue has been resolved in the modernized **v2 architecture** developed under the new **[OpenWebNet-HA](https://github.com/OpenWebNet-HA)** community organization:
- Addressed in **[Pull Request #232 (`v2-phase1-architecture`)](https://github.com/OpenWebNet-HA/MyHOME/pull/232)** and merged core commits.
- Resolved by declarative hardware profiles, token-bucket queue pacing, connection watchdog hardening, and canonical entity registry migration.

If you would like to test, please download or switch to the `v2-phase1-architecture` branch in HACS. If you encounter any remaining issues on this build, please feel free to report them in [PR #232](https://github.com/OpenWebNet-HA/MyHOME/pull/232).
