### ISSUE TITLE
Data received is not a message: None

### ISSUE THREAD

**Issue by 1achy** [OpenWebNet-HA/MyHOME#47]
I have this error but integrartion is work :

Logger: custom_components.myhome
Source: custom_components/myhome/gateway.py:119
Integration: MyHome (documentation, issues)
First occurred: 17:15:11 (10 occurrences)
Last logged: 18:23:12

Data received is not a message: None

How it is fix=?

**Comment by 1achy** [comment]
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.myhome
Source: /usr/local/lib/python3.9/site-packages/OWNd/connection.py:594
Integration: MyHome (documentation, issues)
First occurred: 17:15:11 (10 occurrences)
Last logged: 18:23:12

Event session crashed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/OWNd/connection.py", line 582, in get_next
    return OWNMessage.parse(data.decode())
  File "/usr/local/lib/python3.9/site-packages/OWNd/message.py", line 172, in parse
    return OWNCommand.parse(data)
  File "/usr/local/lib/python3.9/site-packages/OWNd/message.py", line 1608, in parse
    return OWNGatewayCommand(data)
  File "/usr/local/lib/python3.9/site-packages/OWNd/message.py", line 1876, in __init__
    if self._dimension_value[3][0] == "0"
IndexError: list index out of range

**Comment by anotherjulien** [comment]
Any idea what was the actual message that caused this?
I would assume that it is something in WHO 13, but knowing what the message is would help

**Comment by marcob79** [comment]
in case of further information, maybe this document could help
[https://developer.legrand.com/uploads/2019/12/WHO_13.pdf](url)

**Comment by GreenGrassBlueOcean** [comment]
Thank you for your contribution.

We are closing this ticket as part of the transition to the **[OpenWebNet-HA](https://github.com/OpenWebNet-HA)** community repository. This issue relates to legacy YAML configuration (`myhome.yaml`) or older Home Assistant versions that have been superseded by modern UI-based configuration and dynamic auto-discovery.

If you are running the modern integration on Home Assistant 2024+ and still encounter an issue, please feel free to open a fresh ticket with updated logs.
