### ISSUE TITLE
Error and lost connection…

### ISSUE THREAD

**Issue by manueltn78** [OpenWebNet-HA/MyHOME#67]
Hi, I have lot of issue with ntegratin since last 5-6 months…
I have to reload or to reboot ha to make it working again.
I’m connecting to Mh201
Someone have  #solved?
Here some errors:

Logger: homeassistant
Source: custom_components/myhome/climate.py:458 
Integration: MyHome 
First occurred: 13:27:54 (1 occurrences) 
Last logged: 13:27:54

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/myhome/gateway.py", line 231, in listening_loop
    ].handle_event(message)
  File "/config/custom_components/myhome/climate.py", line 458, in handle_event
    self._attr_hvac_action = HVACAction.HEAT
  File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: HEAT

Questo errore ha avuto origine da un'integrazione personalizzata
Logger: custom_components.myhome
Source: custom_components/myhome/gateway.py:323 
Integration: MyHome (documentation, issues) 
First occurred: 13:58:05 (1 occurrences) 
Last logged: 13:58:05

Could not send message *4*311*6##.

Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.myhome
Source: custom_components/myhome/gateway.py:314 
Integration: MyHome (documentation, issues) 
First occurred: 13:00:29 (4 occurrences) 
Last logged: 13:00:36

Command session connection refused, retrying in 1s.
Command session connection refused, retrying in 2s.
Command session connection refused, retrying in 4s.
Command session connection refused, retrying in 6s.

**Comment by manueltn78** [comment]
Some new errors...


Logger: custom_components.myhome
Source: custom_components/myhome/gateway.py:233
Integration: MyHome (documentation, issues)
First occurred: 15:00:48 (302 occurrences)
Last logged: 20:01:12

Unknown device: WHO=4 WHERE=6
Unknown device: WHO=4 WHERE=2
Unknown device: WHO=4 WHERE=3
Unknown device: WHO=4 WHERE=5
Unknown device: WHO=4 WHERE=1

**Comment by manueltn78** [comment]
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: homeassistant
Source: custom_components/myhome/climate.py:458 
Integration: MyHome (documentation, issues) 
First occurred: 19:30:00 (1 occurrences) 
Last logged: 19:30:00

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/myhome/gateway.py", line 231, in listening_loop
    ].handle_event(message)
  File "/config/custom_components/myhome/climate.py", line 458, in handle_event
    self._attr_hvac_action = HVACAction.HEAT
  File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: HEAT

**Comment by bubez81** [comment]
same problem here

**Comment by caiosweet** [comment]
see #65

**Comment by manueltn78** [comment]
> see #65

Now I try

**Comment by manueltn78** [comment]
Also with #65 it does not works, I get no error, but only climate items didn't update.
But If I reload integration and scan scs bus with another app on smartphone, then they update immediatly

**Comment by caiosweet** [comment]
ok, after 2022.8 you need to create a start up automation. see #59

**Comment by manueltn78** [comment]
> ok, after 2022.8 you need to create a start up automation. see #59

I made automation, but still not works, maybe the problem is the gateway I'm using: mh201 ?

**Comment by caiosweet** [comment]
I don’t know.
I also have mh201.
After editing the file with the right attribute names, (`HVACAction.HEATING` and `HVACAction.COOLING`) I rebooted the system and everything is fine.

**Comment by manueltn78** [comment]
> I don’t know. I also have mh201. After editing the file with the right attribute names, (`HVACAction.HEATING` and `HVACAction.COOLING`) I rebooted the system and everything is fine.

I also re edited climate.py and rebooted...
Now it started, let's see....

**Comment by GreenGrassBlueOcean** [comment]
Thank you for your contribution.

We are closing this ticket as part of the transition to the **[OpenWebNet-HA](https://github.com/OpenWebNet-HA)** community repository. This issue relates to legacy YAML configuration (`myhome.yaml`) or older Home Assistant versions that have been superseded by modern UI-based configuration and dynamic auto-discovery.

If you are running the modern integration on Home Assistant 2024+ and still encounter an issue, please feel free to open a fresh ticket with updated logs.
