### ISSUE TITLE
First Setup issue

### ISSUE THREAD

**Issue by danicrist** [OpenWebNet-HA/MyHOME#90]
Hi everyone,
I'm setting up the myhome addon for the first time.
I tried to insert a light but from an error, 
what am I doing wrong? :)

thank you all!

from the registry it gives me:
Loggers: homeassistant.config_entries
Source: custom_components/myhome/__init__.py:51
Integration: MyHome (documentation, issues)
First occurred: 14:58:57 (4 occurrences)
Last logged: 15:06:20

Error setting up entry F454 Gateway for my home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myhome/__init__.py", line 51, in async_setup_entry
    _validated_config = config_schema(yaml.safe_load(await yaml_file.read()))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/parser.py", line 171, in parse_document_start
    raise ParserError(None, None,
yaml.parser.ParserError: expected '<document start>', but found '<block mapping start>'
  in "<unicode string>", line 2, column 3:
      mac: '00:03:xxxxxxxxx'
      ^

**Comment by anotherjulien** [comment]
There is a syntax error in your yaml file, but I cannot tell you what the error is from this snippet alone.

**Comment by danicrist** [comment]
> There is a syntax error in your yaml file, but I cannot tell you what the error is from this snippet alone.

Thanks, I'm sure I'm doing something wrong :) this is yaml:

f454:
  mac: '00:03:50:xx:xx:xx'
  light:
    Stanza Bea:
      where: '85'
      name: Plafoniera
      dimmable: False
      manufacturer: BTicino
      model: F411/4
    Bagno Grande:
      where: '74'
      name: Bagno Grande
      dimmable: False
      manufacturer: BTicino
      model: F411/4

**Comment by anotherjulien** [comment]
Well, you are missing indentation spaces at the beginning of almost all the lines.
Also, I think you cannot have spaces in the keys (so "Stanza Bea:" is not valid; ideally it would be `stanza_bea:`)

**Comment by GreenGrassBlueOcean** [comment]
Thank you for your contribution.

We are closing this ticket as part of the transition to the **[OpenWebNet-HA](https://github.com/OpenWebNet-HA)** community repository. This issue relates to legacy YAML configuration (`myhome.yaml`) or older Home Assistant versions that have been superseded by modern UI-based configuration and dynamic auto-discovery.

If you are running the modern integration on Home Assistant 2024+ and still encounter an issue, please feel free to open a fresh ticket with updated logs.
