### ISSUE TITLE
ERRORE COSA SBAGLIO AIUTO

### ISSUE THREAD

**Issue by Francescol10** [OpenWebNet-HA/MyHOME#98]
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: homeassistant.config_entries
Source: custom_components/myhome/validate.py:177 
Integration: MyHome (documentation, issues) 
First occurred: 01:50:39 (1 occurrences) 
Last logged: 01:50:39

Error setting up entry MYHOMESERVER1 Gateway for myhome
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 561, in validate_dict
    raise er.DictInvalid('expected a dictionary', path)
voluptuous.error.DictInvalid: expected a dictionary

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myhome/__init__.py", line 51, in async_setup_entry
    _validated_config = config_schema(yaml.safe_load(await yaml_file.read()))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myhome/validate.py", line 177, in __call__
    data = super().__call__(data)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 276, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: expected a dictionary

**Comment by GreenGrassBlueOcean** [comment]
Thank you for your contribution.

We are closing this ticket as part of the transition to the **[OpenWebNet-HA](https://github.com/OpenWebNet-HA)** community repository. This issue relates to legacy YAML configuration (`myhome.yaml`) or older Home Assistant versions that have been superseded by modern UI-based configuration and dynamic auto-discovery.

If you are running the modern integration on Home Assistant 2024+ and still encounter an issue, please feel free to open a fresh ticket with updated logs.
